/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.votiverp.core;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class VotiveAPITest {
    @Test void someLibraryMethodReturnsTrue() {
        VotiveAPI classUnderTest = new VotiveAPI();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
